import { Open_Sans } from "next/font/google";
import "./globals.css";
import NavBar from "./_components/navbar";

const openSans = Open_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Ravi Nain",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={openSans.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
